;INSTITUTO TECNOLOGICO SUPERIOR DE VALLADOLID (ITSVA)
;LENGUAJES Y AUTOMATAS II, UNIDAD 4.
;M.M.M.D. JOSE LEONEL PECH MAY.
;BR. LUIS ADRIAN BALAM ESPADAS.
;EJERCICIO 2, COMPARACION DE 3 NUMEROS.
;FECHA DE ENTREGA: LUNES, 13 DE MAYO DE 2019.

.model small 

.stack 100

.data 
    
    ;INCLUIMOS EL ARCHIVO INICIALIZADOR DEL SOFTWARE.
    ;DECLARACION DE LOS TEXTOS QUE  SE IMPRIMEN.
    IMPRESION1 DB 0AH,0DH, 'A CONTINUACION, INGRESE TRES VALORES DISTINTOS: ', '$'
    IMPRESION2 DB 0AH,0DH, 'PRIMER VALOR: ', '$'
    IMPRESION3 DB 0AH,0DH, 'SEGUNDO VALOR: ', '$'
    IMPRESION4 DB 0AH,0DH, 'TERCER VALOR: ', '$'
    NUMEROMAYOR DB 0AH,0DH, 'EN BASE AL PROCESO DE ANALISIS, EL NUMERO MAYOR ES: ', '$'
    VALORINGRESADO1 DB 100 DUP('$')
    VALORINGRESADO2 DB 100 DUP('$')
    VALORINGRESADO3 DB 100 DUP('$')
    SALTOLINEA DB 13,10,13,10,'$'
    ESPACIO DB 9,'$'
    
.code 

inicio:
    call PINTARPANTALLA
    mov si,0
    mov ax,@data
    mov ds,ax
    mov ah,09
    mov dx,offset IMPRESION1
    int 21h
    call SALTARLINEA
    call SOLICITARVALOR
    mov VALORINGRESADO1,al
    call DEJARESPACIO
    call SOLICITARVALOR
    mov VALORINGRESADO2,al 
    call DEJARESPACIO
    call SOLICITARVALOR
    mov VALORINGRESADO3,al
    call SALTARLINEA
    
    ;PROCEDIMIENTO PARA COMPARAR VALORES.
    mov ah,VALORINGRESADO1
    mov al,VALORINGRESADO2
    cmp ah,al 
    ja COMPARACION1 
    jmp COMPARACION2 

COMPARACION1:
    mov al,VALORINGRESADO3 
    cmp ah,al 
    ja PRIMEROMAYOR

COMPARACION2:
    mov ah,VALORINGRESADO2
    mov al,VALORINGRESADO3
    cmp ah,al 
    ja SEGUNDOMAYOR
    jmp TERCEROMAYOR

PRIMEROMAYOR:
    call RESULTADOMAYOR
    mov dx,offset VALORINGRESADO1
    mov ah,9
    int 21h
    jmp SALIRPROG

SEGUNDOMAYOR:
    call RESULTADOMAYOR
    mov dx,offset VALORINGRESADO2
    mov ah,9
    int 21h
    jmp SALIRPROG

TERCEROMAYOR:
    call RESULTADOMAYOR
    mov dx,offset VALORINGRESADO3
    mov ah,9
    int 21h
    jmp SALIRPROG

;METODOS QUE EJECUTAN ACCIONES PARA EL PROGRAMA.
PINTARPANTALLA: 
    MOV AH,06H
    MOV AL,0
    MOV BH,1FH
    MOV CX,0000H
    MOV DX,1850H
    INT 10H

DEJARESPACIO:
    mov dx,OFFSET ESPACIO
    mov ah,9
    int 21H
    ret
    
RESULTADOMAYOR:
    mov dx,OFFSET NUMEROMAYOR
    mov ah,9
    int 21H 
    ret
    
SOLICITARVALOR:
    mov ah,01h
    int 21H
    ret
    
SALTARLINEA:
    mov dx,OFFSET SALTOLINEA
    mov ah,9
    int 21H
    ret
    
SALIRPROG:
    mov ax, 4c00h
    int 21h
    ends