;INSTITUTO TECNOLOGICO SUPERIOR DE VALLADOLID (ITSVA)
;LENGUAJES Y AUTOMATAS II, UNIDAD 4.
;M.M.M.D. JOSE LEONEL PECH MAY.
;BR. LUIS ADRIAN BALAM ESPADAS.
;EJERCICIO 1, OPERACIONES ARITMETICAS.
;FECHA DE ENTREGA: LUNES, 13 DE MAYO DE 2019.

.MODEL SMALL

.STACK 100

.DATA 
      
    ;TEXTOS EMPLEADOS EN EL PROGRAMA.
    IMPRESION1 DB 'INGRESA EL PRIMER VALOR: ','$'
    IMPRESION2 DB 13,10,'INGRESA EL SEGUNDO VALOR: ','$'
    IMPRESION3 DB 13,10,'RESULTADO DE LA SUMA: ','$'     
    IMPRESION4 DB 13,10,'RESULTADO DE LA RESTA: ','$'     
    IMPRESION5 DB 13,10,'RESULTADO DE LA MULTIPLICACION: ','$' 
    IMPRESION6 DB 13,10,'RESULTADO DE LA DIVISION: ','$'
    ELEMENTOIMP DB 13,10,'$'
    VALORUSUARIO1 DB 0
    VALORUSUARIO2 DB 0
         
.CODE 

.STARTUP

    ;METODO PARA PINTAR LA PANTALLA 
    MOV AH,06H
    MOV AL,0
    MOV BH,1FH
    MOV CX,0000H
    MOV DX,1850H
    INT 10H  
    
    ;LLAMAR AL APARTADO LIMPIAR PARA IMPRIMIR EL PRIMER TEXTO.
    CALL LIMPIA
    MOV AH,09H
    LEA DX,IMPRESION1
    INT 21H
      
    ;LEEMOS LA INFORMACION DEL PRIMER VALOR.
    CALL LEER
    SUB AL,30H
    MOV VALORUSUARIO1,AL
    MOV AH,09H
    LEA DX,IMPRESION2
    INT 21H
   
    ;LEEMOS LA INFORMACION DEL SEGUNDO VALOR.
    CALL LEER
    SUB AL,30H
    MOV VALORUSUARIO2,AL
    MOV BL,VALORUSUARIO2
 
    ;PROCEDIMIENTO DE LA SUMA
    ADD BL,VALORUSUARIO1
    MOV AH,09H
    LEA DX,IMPRESION3
    INT 21H
    MOV DL,BL
    ADD DL,30H
    MOV AH,02H
    INT 21H

    ;PROCEDIMIENTO DE LA RESTA
    MOV BL,VALORUSUARIO1
    SUB BL,VALORUSUARIO2
    MOV AH,09H
    LEA DX,IMPRESION4
    INT 21H
    MOV DL,BL
    ADD DL,30H
    MOV AH,02H
    INT 21H

    ;PROCEDIMIENTO DE LA MULTIPLICACION
    MOV AH,09H
    LEA DX, IMPRESION5
    INT 21H
    MOV AL,VALORUSUARIO1
    MOV BL,VALORUSUARIO2
    MUL BL
    MOV DL,AL
    ADD DL,30H
    MOV AH,02H
    INT 21H

    ;PROCEDIMIENTO DE LA DIVISION
    MOV AH,09H
    LEA DX, IMPRESION6
    INT 21H
    XOR AX,AX
    MOV AL,VALORUSUARIO2
    MOV BL,AL
    MOV AL,VALORUSUARIO1
    DIV BL
    MOV BL,AL
    MOV DL,BL
    ADD DL,30H
    MOV AH,02H
    INT 21H
.EXIT

;PROCEDIMIENTOS EXTRAS
SALTO PROC NEAR   
    MOV AH,09H
    LEA DX,ELEMENTOIMP
    INT 21H
    MOV DL,00H
    RET
SALTO ENDP
    
LEER PROC NEAR
    MOV AH,01H
    INT 21H
    RET 
LEER ENDP   
    
LIMPIA PROC NEAR
    MOV AH,00H
    MOV AL,03H
    INT 10H
    RET
LIMPIA ENDP

    END
