;INSTITUTO TECNOLOGICO SUPERIOR DE VALLADOLID (ITSVA).
;ING. EN SISTEMAS COMPUTACIONALES (ISC, 6"A").
;LENGUAJES Y AUTOMATAS II, U4.
;M.M.M.D. JOSE LEONEL PECH MAY.
;EJERCICIO 4, MENU.
;BR. LUIS ADRIAN BALAM ESPADAS.
;LUNES, 13 DE MAYO DE 2019. 

.MODEL SMALL

.DATA 

    TITULOMENU db "U4EJ4. MENU DE OPCIONES$"
    OP1 db "(1) OPERACIONES ARITMETICAS$"
    OP2 db "(2) MAYOR DE 3 NUMEROS$"
    OP3 db "(3) SALIR$"
    SUBTITULOMENU db "SELECCIONE UNA OPCION:$"
    ;TEXTOS EMPLEADOS EN EL PROGRAMA 1.
    IMPRESION1 DB 'INGRESA EL PRIMER VALOR: ','$'
    IMPRESION2 DB 13,10,'INGRESA EL SEGUNDO VALOR: ','$'
    IMPRESION3 DB 13,10,'RESULTADO DE LA SUMA: ','$'     
    IMPRESION4 DB 13,10,'RESULTADO DE LA RESTA: ','$'     
    IMPRESION5 DB 13,10,'RESULTADO DE LA MULTIPLICACION: ','$' 
    IMPRESION6 DB 13,10,'RESULTADO DE LA DIVISION: ','$'
    ELEMENTOIMP DB 13,10,'$'
    VALORUSUARIO1 DB 0
    VALORUSUARIO2 DB 0
    ;DECLARACION DE LOS TEXTOS QUE  SE IMPRIMEN EN EL PROGRAMA 2.
    IMPRESION11 DB 0AH,0DH, 'A CONTINUACION, INGRESE TRES VALORES DISTINTOS: ', '$'
    IMPRESION22 DB 0AH,0DH, 'PRIMER VALOR: ', '$'
    IMPRESION33 DB 0AH,0DH, 'SEGUNDO VALOR: ', '$'
    IMPRESION44 DB 0AH,0DH, 'TERCER VALOR: ', '$'
    NUMEROMAYOR DB 0AH,0DH, 'EN BASE AL PROCESO DE ANALISIS, EL NUMERO MAYOR ES: ', '$'
    VALORINGRESADO1 DB 100 DUP('$')
    VALORINGRESADO2 DB 100 DUP('$')
    VALORINGRESADO3 DB 100 DUP('$')
    SALTOLINEA DB 13,10,13,10,'$'
    ESPACIO DB 9,'$'
  
.CODE
    
    MOV AX,@DATA
    MOV DS,AX  
    
    ;BLOQUE DE CODIGO QUE DEFINE COLOR, GENERAL 
    MOV AH,06H
    MOV AL,25
    MOV BH,07H;COLOR FONDO/TEXTO
    MOV CX,0000H;COORDENADA X,Y DE LA ESQUINA IZQ SUPERIOR (80,25 RESOLUCION X,Y)
    MOV DX,184FH;COORDENADA X,Y DE LA ESQUINA INF DERECHA (80,25 RESOLUCION X,Y)
    INT 10H 
    
    ;BLOQUE DE CODIGO QUE DEFINE COLOR, ENCABEZADO
    MOV AH,06H
    MOV AL,0
    MOV BH,2AH
    MOV CX,040AH
    MOV DX,043BH
    INT 10H
    
    ;BLOQUE DE CODIGO QUE DEFINE COLOR, RECUADRO CENTRAL
    MOV AH,06H
    MOV AL,0
    MOV BH,2AH
    MOV CX,060AH
    MOV DX,133BH
    INT 10H 
     
    ;BLOQUE DE CODIGO QUE MANEJA POSICION CURSOR PARA ESCRIBIR, TITULO 
    MOV AH,02H;ESTA FUNCION PERMITE POSICIONAR EL CURSOR DE FORMA PERSONALIZADA.
    MOV BH,0 ;LE INDICA DONDE SE VA A POSICIONAR EL CURSOR
    MOV DH,04H;FILA DEL TEXTO
    MOV DL,18H;COLUMNA DEL TEXTO
    INT 10H
    
    MOV AH,09H
    MOV DX,OFFSET TITULOMENU ;IMPRIME EL TEXTO O VALOR
    INT 21H 
    
    ;BLOQUE DE CODIGO QUE MANEJA POSICION CURSOR PARA ESCRIBIR, TITULO 
    MOV AH,02H;ESTA FUNCION PERMITE POSICIONAR EL CURSOR DE FORMA PERSONALIZADA.
    MOV BH,0 ;LE INDICA DONDE SE VA A POSICIONAR EL CURSOR
    MOV DH,08H
    MOV DL,0CH
    INT 10H 
    
    MOV AH,09H
    MOV DX,OFFSET OP1
    INT 21H
    
    ;BLOQUE DE CODIGO QUE MANEJA POSICION CURSOR PARA ESCRIBIR, TITULO 
    MOV AH,02H;ESTA FUNCION PERMITE POSICIONAR EL CURSOR DE FORMA PERSONALIZADA.
    MOV BH,0 ;LE INDICA DONDE SE VA A POSICIONAR EL CURSOR
    MOV DH,0AH
    MOV DL,0CH
    INT 10H
    
    MOV AH,09H
    MOV DX,OFFSET OP2
    INT 21H
    
    ;BLOQUE DE CODIGO QUE MANEJA POSICION CURSOR PARA ESCRIBIR, TITULO 
    MOV AH,02H;ESTA FUNCION PERMITE POSICIONAR EL CURSOR DE FORMA PERSONALIZADA.
    MOV BH,0 ;LE INDICA DONDE SE VA A POSICIONAR EL CURSOR
    MOV DH,0CH
    MOV DL,0CH
    INT 10H
    
    MOV AH,09H
    MOV DX,OFFSET OP3
    INT 21H
    
    ;BLOQUE DE CODIGO QUE MANEJA POSICION CURSOR PARA ESCRIBIR, TITULO 
    MOV AH,02H;ESTA FUNCION PERMITE POSICIONAR EL CURSOR DE FORMA PERSONALIZADA.
    MOV BH,0 ;LE INDICA DONDE SE VA A POSICIONAR EL CURSOR
    MOV DH,15H
    MOV DL,20H
    INT 10H
    
    MOV AH,09H
    MOV DX,OFFSET SUBTITULOMENU
    INT 21H  
    
    LEER1:
    ;CON ESTAS DOS LINEAS DE CODIGO SE HABILITA EL 'SCANNER' EN ENSAMBLADOR
    MOV AH,00H
    INT 16H
          
    ;VALORES A EVALUAR Y ACCIONES 'JUMP' A LA ETIQUETA CORRESPONDIENTE     
    CMP AL,49
    JE OPCION1
    CMP AL,50
    JE OPCION2
    CMP AL,51
    JE FINPROG
    
    OPCION1:
         
    ;CON ESTA LINEA SE DEFINE QUE PAGINA DEL PROGRAMA VER     
    MOV AH,05H
    MOV AL,1;ESTA LINEA DEFINE EL NUMERO DE PAGINA (LA 0 ES LA PRIMERA DONDE PROGRAMAMOS, ES DECIR, EL MENU)
    INT 10H 
    
    ;METODO PARA PINTAR LA PANTALLA 
    MOV AH,06H
    MOV AL,0
    MOV BH,1FH
    MOV CX,0000H
    MOV DX,1850H
    INT 10H  
    
    ;LLAMAR AL APARTADO LIMPIAR PARA IMPRIMIR EL PRIMER TEXTO.
    CALL LIMPIA
    MOV AH,09H
    LEA DX,IMPRESION1
    INT 21H
      
    ;LEEMOS LA INFORMACION DEL PRIMER VALOR.
    CALL LEER
    SUB AL,30H
    MOV VALORUSUARIO1,AL
    MOV AH,09H
    LEA DX,IMPRESION2
    INT 21H
   
    ;LEEMOS LA INFORMACION DEL SEGUNDO VALOR.
    CALL LEER
    SUB AL,30H
    MOV VALORUSUARIO2,AL
    MOV BL,VALORUSUARIO2
 
    ;PROCEDIMIENTO DE LA SUMA
    ADD BL,VALORUSUARIO1
    MOV AH,09H
    LEA DX,IMPRESION3
    INT 21H
    MOV DL,BL
    ADD DL,30H
    MOV AH,02H
    INT 21H

    ;PROCEDIMIENTO DE LA RESTA
    MOV BL,VALORUSUARIO1
    SUB BL,VALORUSUARIO2
    MOV AH,09H
    LEA DX,IMPRESION4
    INT 21H
    MOV DL,BL
    ADD DL,30H
    MOV AH,02H
    INT 21H

    ;PROCEDIMIENTO DE LA MULTIPLICACION
    MOV AH,09H
    LEA DX, IMPRESION5
    INT 21H
    MOV AL,VALORUSUARIO1
    MOV BL,VALORUSUARIO2
    MUL BL
    MOV DL,AL
    ADD DL,30H
    MOV AH,02H
    INT 21H

    ;PROCEDIMIENTO DE LA DIVISION
    MOV AH,09H
    LEA DX, IMPRESION6
    INT 21H
    XOR AX,AX
    MOV AL,VALORUSUARIO2
    MOV BL,AL
    MOV AL,VALORUSUARIO1
    DIV BL
    MOV BL,AL
    MOV DL,BL
    ADD DL,30H
    MOV AH,02H
    INT 21H
    
    JMP FINPROG
     
    OPCION2:
    
    MOV AH,05H
    MOV AL,2
    INT 10H
    
    call PINTARPANTALLA
    mov si,0
    mov ax,@data
    mov ds,ax
    mov ah,09
    mov dx,offset IMPRESION11
    int 21h
    call SALTARLINEA
    call SOLICITARVALOR
    mov VALORINGRESADO1,al
    call DEJARESPACIO
    call SOLICITARVALOR
    mov VALORINGRESADO2,al 
    call DEJARESPACIO
    call SOLICITARVALOR
    mov VALORINGRESADO3,al
    call SALTARLINEA
    
    ;PROCEDIMIENTO PARA COMPARAR VALORES.
    mov ah,VALORINGRESADO1
    mov al,VALORINGRESADO2
    cmp ah,al 
    ja COMPARACION1 
    jmp COMPARACION2 

COMPARACION1:
    mov al,VALORINGRESADO3 
    cmp ah,al 
    ja PRIMEROMAYOR

COMPARACION2:
    mov ah,VALORINGRESADO2
    mov al,VALORINGRESADO3
    cmp ah,al 
    ja SEGUNDOMAYOR
    jmp TERCEROMAYOR

PRIMEROMAYOR:
    call RESULTADOMAYOR
    mov dx,offset VALORINGRESADO1
    mov ah,9
    int 21h
    jmp FINPROG

SEGUNDOMAYOR:
    call RESULTADOMAYOR
    mov dx,offset VALORINGRESADO2
    mov ah,9
    int 21h
    jmp FINPROG

TERCEROMAYOR:
    call RESULTADOMAYOR
    mov dx,offset VALORINGRESADO3
    mov ah,9
    int 21h    
    jmp FINPROG
    
;METODOS QUE EJECUTAN ACCIONES PARA EL PROGRAMA.
PINTARPANTALLA: 
    MOV AH,06H
    MOV AL,0
    MOV BH,1FH
    MOV CX,0000H
    MOV DX,1850H
    INT 10H

DEJARESPACIO:
    mov dx,OFFSET ESPACIO
    mov ah,9
    int 21H
    ret
    
RESULTADOMAYOR:
    mov dx,OFFSET NUMEROMAYOR
    mov ah,9
    int 21H 
    ret
    
SOLICITARVALOR:
    mov ah,01h
    int 21H
    ret
    
SALTARLINEA:
    mov dx,OFFSET SALTOLINEA
    mov ah,9
    int 21H
    ret
    
    FINPROG:
    
    ;ESTAS DOS LINEAS DE INSTRUCCION TERMINAN EL PROGRAMA     
    MOV AH,4CH
    INT 21H  
    
.EXIT   

;PROCEDIMIENTOS EXTRAS
SALTO PROC NEAR   
    MOV AH,09H
    LEA DX,ELEMENTOIMP
    INT 21H
    MOV DL,00H
    RET
SALTO ENDP
    
LEER PROC NEAR
    MOV AH,01H
    INT 21H
    RET 
LEER ENDP   
    
LIMPIA PROC NEAR
    MOV AH,00H
    MOV AL,03H
    INT 10H
    RET
LIMPIA ENDP

    END